### ISSUE TITLE
username variable issues with ansible > 2.2.0.0

### ISSUE THREAD

**Issue by jduncan-rva** [ansible/lightbulb#216]
The following task in manage_ec2_instances/tasks/create.yml:

```
- name: Set local username to create on instances
  set_fact:
    username: "{{ item | regex_replace('.*-(\\w*)-\\w*$','\\1') }}"
  with_items: "{{ groups.lab_hosts }}"
  delegate_to: "{{ item }}"
  delegate_facts: yes
  tags:
    - always
    - provision
```

It looks like this regex fails on any newer version of ansible, this causes the user group and user tasks to fail later. 

Can we refactor this to work with newer versions, 2.2.2.0 which is required for the OpenShift installer.
