### ISSUE TITLE
Slide deck wording does not align with the example that follows

### ISSUE THREAD

**Issue by dswhitley** [ansible/lightbulb#224]
The text on slide 33 of the ansible-essentials.html deck states:

> If a configuration file gets changed notify a service restart task that it needs to run.

But the example on the following slide (34) shows a handler utilized on the task that installs a package.

The example would make more sense in relation to the prior slide if the `notify` was in the "copy" task:

```
- name: latest index.html file is present
  copy:
    src: files/index.html
    dest: /var/www/html/
  notify: restart httpd
```

Additionally, the `package` module could be used in place of `yum` but that is purely personal preference.
