### ISSUE TITLE
Nginx workshop missing instruction to enable corresponding repo

### ISSUE THREAD

**Issue by webknjaz** [ansible/lightbulb#282]
Either
```
yum install epel-release
```

or
```yaml
- name: Add nginx repository
  yum_repository:
    name: nginx
    description: NginX YUM repo
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    gpgcheck: no
```

in playbook
